# Generated by Django 5.1.4 on 2024-12-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.URLField()),
                ("price_band", models.CharField(max_length=100)),
                ("opening_date", models.DateField()),
                ("closing_date", models.DateField()),
                ("issue_size", models.FloatField()),
                ("issue_type", models.CharField(max_length=100)),
                ("listing_date", models.DateField()),
                ("status", models.CharField(max_length=100)),
                ("ipo_price", models.FloatField()),
                ("listing_price", models.FloatField()),
                ("listing_gain", models.FloatField()),
                ("current_market_price", models.FloatField()),
                ("current_return", models.FloatField()),
                ("rhp_pdf", models.FileField(upload_to="rhp_pdfs/")),
                ("drhp_pdf", models.FileField(upload_to="drhp_pdfs/")),
            ],
        ),
    ]
